front_controllers:
    resource: ../../src/Controller/Front/
    type: annotation
    prefix: /

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
