name: PHP Code Style
on: [push, pull_request]
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP Coding Standards Fixer
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, propro, raphf, http
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: php-actions/composer@v4
        with:
          composer_version: 1
          args: --prefer-dist
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, propro, raphf, http
